--- #YAML:1.0
name:               OpenGL
version:            0.65
abstract:           Perl bindings to the OpenGL API, GLU, and GLUT/FreeGLUT
author:
    - Chris Marshall <chm at cpan dot org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    bugtracker:  http://sourceforge.net/tracker/?group_id=562483&atid=2281758
    homepage:    http://sourceforge.net/projects/pogl/
    repository:  git://pogl.git.sourceforge.net/gitroot/pogl/pogl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
