#!make

CC= gcc
OPTIMIZER= -g
CFLAGS=  $(OPTIMIZER) -DXP_UNIX -DPLUGIN_TRACE -I. -I/usr/include -I/usr/openwin/include -I/usr/dt/include

SRC= npunix.c npshell.c 
OBJ= npunix.o npshell.o

.c.o:
	$(CC) -c $(CFLAGS) $<

SHAREDTARGET=libopenglplugin.so

default all: $(SHAREDTARGET)

$(SHAREDTARGET): $(OBJ)
	$(CC) -shared -o $(SHAREDTARGET) $(OBJ) $(LDFLAGS)

clean:
	$(RM) $(OBJ) $(SHAREDTARGET)


